### ISSUE TITLE
forkしたリポジトリのupstreamの更新方法がわかっていない

### ISSUE THREAD

**Issue by korosuke613** [KatLab-MiyazakiUniv/etrobocon2018#12]
**あなたの機能リクエストは問題に関連していますか？記述してください。**
メンバがforkしたリポジトリのupstreamの更新方法がわかっていない。

**あなたが望むソリューションを記述する**
~READMEに記述。~
Wikiに記述。(2018/07/30追記)

**Comment by Morichan** [comment]
READMEではなくWikiに書いていただけませんか......？

**Comment by korosuke613** [comment]
Thanks @Morichan 
Exactly.
I edited issue.

**Comment by korosuke613** [comment]
[Wiki](https://github.com/KatLab-MiyazakiUniv/etrobocon2018/wiki/forkしたリポジトリに、fork元リポジトリの変更を加える方法)に方法を記述しました。
