### ISSUE TITLE
READMEのREADME化

### ISSUE THREAD

**Issue by Morichan** [KatLab-MiyazakiUniv/etrobocon2018#16]
**あなたの機能リクエストは問題に関連していますか？記述してください。**

現在のREADMEはプログラム自体のREADMEではなく、このリポジトリを正しくForkする手法のREADMEであり、READMEとしての体裁を保っていません。

**あなたが望むソリューションを記述する**

* 現在のREADMEの内容はWikiなどに移動
* 新しいREADMEにはこのプログラムの使い方や存在理由などの説明を記述

追記:
make方法についてはこのままでもいいと思います。

**Comment by korosuke613** [comment]
Thanks @Morichan 
It is a problem I want to deal with as soon as possible.
