### ISSUE TITLE
Wikiページにおける画像URLの不備

### ISSUE THREAD

**Issue by Morichan** [KatLab-MiyazakiUniv/etrobocon2018#26]
**バグを記述する**
https://github.com/KatLab-MiyazakiUniv/etrobocon2018/wiki/fork方法 における画像が全て見ることができません。
バグとはちょっと違うんですけど......

**スクリーンショット**
![スクリーンショット](https://user-images.githubusercontent.com/20200292/43488961-5794f8a4-9556-11e8-8e42-b0dfdbdd1a31.png)

**デスクトップ（以下の情報を記入してください）：**
  -  OS：Windows 10
  - ブラウザ：Chrome

**Comment by korosuke613** [comment]
[該当ページ](https://github.com/KatLab-MiyazakiUniv/etrobocon2018/wiki/fork方法)を修正しました。
