### ISSUE TITLE
Workerクラスの名前が紛らわしい

### ISSUE THREAD

**Issue by Morichan** [KatLab-MiyazakiUniv/etrobocon2018#34]
**バグを記述する**

現在はWorkerクラスとWalkerクラスが同時に存在し、その呼び名が非常にややこしいです。
Workerクラスを別の名前にできないでしょうか？

**予想される行動**

Workerクラスを、APIクラスやControllerクラスやUtilityクラスに名前を変更
変更後は抜かりなく各メンバーに通達

**Comment by korosuke613** [comment]
Oh...

Exactly.
I will change the name.
