### ISSUE TITLE
Application is too Large 問題

### ISSUE THREAD

**Issue by Morichan** [KatLab-MiyazakiUniv/etrobocon2018#77]
**バグを記述する**

std::vectorにおけるいくつかのメンバ関数において、try-catch構文によるメモリ肥大化の発生を観測しています。

**再現するには**

Explorerクラスをインスタンス化する。
容量が6MBを超える。

**予想される行動**

容量が0.7MBを超えない。

**現在分かっている問題点**

Explorerクラスのコンストラクタ内の振舞いが問題です。
具体的な点を2点、下記に記します。

- neighborsIDListメンバ変数にvectorのvectorをコピーする。
  これを防ぎたいのですが、次の問題点により解決策がわかりません。
- neighborPtrs.resize(16)を実行する。
  vectorのvectorをリサイズする際に、内部処理ではメモリサイズの拡張を行います。
  恐らく、サイズが足りない場合に例外を投げている可能性があります。
  これを解決するためにはpush_back関数によりvectorをコピーすればいいのですが、前の問題点により解決策がわかりません。

**Comment by korosuke613** [comment]
この問題は #79 によって解決しました。
